from drf_yasg import openapi
from drf_yasg.utils import swagger_auto_schema
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from backend.api_exceptions import ErrorCommunicatingWithExternalSourceError
from backend.client.guarani_client import GuaraniClient
from backend.permissions import IsStudent

# Maps SIU propuesta IDs to FIUBA-Map career IDs (pre-2020 plans use numeric SIU codes)
PROPUESTA_TO_FIUBA_MAP = {
    1:   'civil',
    2:   'informatica',       # Plan 1986 (numeric SIU codes match directly)
    3:   'alimentos',
    4:   'agrimensura',
    6:   'petroleo',
    7:   'industrial',
    8:   'naval',
    10:  'agrimensura',
    11:  'mecanica',
    12:  'electricista',
    13:  'electronica',
    14:  'quimica',
    15:  'sistemas',
    120: 'electricista',
    126: 'bioingenieria-2020',
}

# Plan 2023 is the new curriculum. Maps propuesta to FIUBA-Map semantic-ID plan.
PROPUESTA_TO_FIUBA_MAP_2023 = {
    2:  'informatica-2020',   # Ingeniería en Informática Plan 2023 → FIUBA-Map "informatica-2020"
    15: 'sistemas',           # LAS has no 2020 plan in FIUBA-Map, use same
}

# Argentine DNI document type and country code in SIU Guaraní
SIU_TIPO_DOCUMENTO_DNI = 0
SIU_PAIS_ARGENTINA = 54

# Maps SIU Plan 2023 activity codes to FIUBA-Map Plan 2020 node IDs.
# Auto-generated by matching subject names, manually completed for unmatched entries.
SIU_2023_TO_FIUBA_MAP_2020 = {
    # Core subjects (CBC and mandatory)
    'CB001': 'AMII',    'CB002': 'AL',      'CB003': 'PYE',     'CB005': 'AMIII',
    'CB024': 'FPI',     'CB051': 'MODNUM',  'CB100': 'AED',     'CB101': 'FMCRIPTO',
    'CBC03': 'CBC3',    'CBC24': 'CBC24',   'CBC40': 'CBC40',   'CBC62': 'CBC62',
    'CBC66': 'CBC66',   'CBC90': 'CBC90',
    # Mandatory (TB)
    'TB021': 'FDP',     'TB022': 'IDS',     'TB023': 'ORGCOMPU','TB024': 'TDA',
    'TB025': 'PDP',     'TB026': 'PROGC',   'TB027': 'LYCI',    'TB028': 'SIM',
    'TB029': 'TADJ',    'TB030': 'TDCOMPU', 'TB031': 'TDLI',    'TB032': 'CC',
    'TB033': 'LYCII',   'TB034': 'ARQSOFT',
    # Electives (TA)
    'TA043': 'SISOPS',  'TA044': 'BDD',     'TA045': 'TDP',     'TA046': 'INGSOFTI',
    'TA047': 'CDD',     'TA048': 'REDES',   'TA049': 'INGSOFTII','TA050': 'SDI',
    'TA051': 'TDSINF',  'TA054': 'CRIPTOI', 'TA055': 'CRIPTOII','TA056': 'SDII',
    'TA057': 'TII',     'TA058': 'CRIPTOAN','TA059': 'IDD',     'TA060': 'OPTCONV',
    'TA061': 'AA',      'TA062': 'AP',      'TA063': 'APR',     'TA064': 'SISTC',
    'TA065': 'REDESC',
    # Business/management electives (TC)
    'TC017': 'GDSI',    'TC018': 'EBTI',    'TC019': 'EBTII',
    # Degree completion
    'TA052': 'TIF',     'TA053': 'TIF',     'PPS-IF-2023': 'TIF',
}


def _siu_code_to_fiuba_map_id(codigo):
    """Converts a SIU activity code to the corresponding FIUBA-Map node ID.

    - Plan 1986: 4-digit numeric codes (e.g. 7540) → XX.YY format (e.g. 75.40)
    - Plan 2023: alphanumeric codes (e.g. CB001, TB021) → looked up in SIU_2023_TO_FIUBA_MAP_2020
    - CBC codes (e.g. CBC62): looked up in the same table; returned as-is if not found
    """
    if not codigo:
        return codigo
    if len(codigo) == 4 and codigo.isdigit():
        return f"{codigo[:2]}.{codigo[2:]}"
    return SIU_2023_TO_FIUBA_MAP_2020.get(codigo, codigo)


class PlanCarreraView(APIView):
    """Returns the student's approved subjects and career from SIU Guaraní.

    Used by the FIUBA-Map mobile integration to pre-populate the career graph
    without requiring the student to enter data manually.
    """
    permission_classes = [IsAuthenticated, IsStudent]

    @swagger_auto_schema(
        tags=["Guarani"],
        operation_summary="Plan de carrera del alumno desde Guaraní",
        responses={
            200: openapi.Response(
                description="Materias aprobadas y carrera del alumno",
                schema=openapi.Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        'carreras': openapi.Schema(
                            type=openapi.TYPE_ARRAY,
                            items=openapi.Schema(
                                type=openapi.TYPE_OBJECT,
                                properties={
                                    'propuesta': openapi.Schema(type=openapi.TYPE_INTEGER),
                                    'propuesta_nombre': openapi.Schema(type=openapi.TYPE_STRING),
                                    'fiuba_map_carrera_id': openapi.Schema(type=openapi.TYPE_STRING, x_nullable=True),
                                },
                            ),
                        ),
                        'materias_aprobadas': openapi.Schema(
                            type=openapi.TYPE_ARRAY,
                            items=openapi.Schema(
                                type=openapi.TYPE_OBJECT,
                                properties={
                                    'id': openapi.Schema(type=openapi.TYPE_STRING, description="FIUBA-Map node ID"),
                                    'nota': openapi.Schema(type=openapi.TYPE_INTEGER),
                                    'nombre': openapi.Schema(type=openapi.TYPE_STRING),
                                },
                            ),
                        ),
                    },
                ),
            ),
            404: openapi.Response(description="Alumno no encontrado en el SIU"),
            503: openapi.Response(description="SIU Guaraní no disponible"),
        },
    )
    def get(self, request):
        dni = request.user.dni
        client = GuaraniClient()

        try:
            personas = client.list_personas(
                tipo_documento=SIU_TIPO_DOCUMENTO_DNI,
                numero_documento=dni,
                pais=SIU_PAIS_ARGENTINA,
            )
        except ErrorCommunicatingWithExternalSourceError:
            return Response(
                {'detail': 'Error al consultar el SIU Guaraní.'},
                status=status.HTTP_503_SERVICE_UNAVAILABLE,
            )

        if not personas or not isinstance(personas, (list, dict)):
            return Response(
                {'detail': 'Alumno no encontrado en el SIU.'},
                status=status.HTTP_404_NOT_FOUND,
            )

        persona_id = (personas[0] if isinstance(personas, list) else personas).get('persona')
        if not persona_id:
            return Response(
                {'detail': 'No se pudo obtener el ID de persona del SIU.'},
                status=status.HTTP_404_NOT_FOUND,
            )

        try:
            analitico = client.get_persona_datos_analitico(persona_id)
        except ErrorCommunicatingWithExternalSourceError:
            return Response(
                {'detail': 'Error al consultar el SIU Guaraní.'},
                status=status.HTTP_503_SERVICE_UNAVAILABLE,
            )

        if analitico is None:
            return Response(
                {'detail': 'Error al consultar el SIU Guaraní.'},
                status=status.HTTP_503_SERVICE_UNAVAILABLE,
            )

        analitico = analitico if isinstance(analitico, list) else []

        # Detect whether the student is on Plan 2023 (alphanumeric codes like CB001, TB021)
        # vs Plan 1986 (4-digit numeric codes like 7540)
        plan_2023_codes = {r.get('actividad_codigo', '') for r in analitico}
        is_plan_2023 = any(
            cod and not (len(cod) == 4 and cod.isdigit()) and not cod.startswith('CBC')
            for cod in plan_2023_codes
        )
        carrera_map = PROPUESTA_TO_FIUBA_MAP_2023 if is_plan_2023 else PROPUESTA_TO_FIUBA_MAP

        # Collect unique careers
        propuestas_vistas = {}
        for item in analitico:
            prop = item.get('propuesta')
            if prop and prop not in propuestas_vistas:
                propuestas_vistas[prop] = item.get('propuesta_nombre', '')

        carreras = [
            {
                'propuesta': prop,
                'propuesta_nombre': nombre,
                'fiuba_map_carrera_id': carrera_map.get(prop),
            }
            for prop, nombre in propuestas_vistas.items()
        ]

        # Collect approved subjects (nota >= 4, numeric grade)
        materias_aprobadas = []
        seen = set()
        for item in analitico:
            nota_raw = item.get('nota', '')
            if not (nota_raw and str(nota_raw).isdigit() and int(nota_raw) >= 4):
                continue
            codigo_siu = item.get('actividad_codigo', '')
            fiuba_map_id = _siu_code_to_fiuba_map_id(codigo_siu)
            key = (fiuba_map_id, int(nota_raw))
            if key in seen:
                continue
            seen.add(key)
            materias_aprobadas.append({
                'id': fiuba_map_id,
                'nota': int(nota_raw),
                'nombre': item.get('actividad_nombre', ''),
            })

        return Response({
            'carreras': carreras,
            'materias_aprobadas': materias_aprobadas,
        })


class OfertaComisionesView(APIView):
    permission_classes = [IsAuthenticated]

    @swagger_auto_schema(
        tags=["Guarani"],
        operation_summary="Lista comisiones con horarios desde Guaraní",
        manual_parameters=[
            openapi.Parameter(
                'actividad_codigo',
                openapi.IN_QUERY,
                description="Código de actividad (materia) para filtrar",
                type=openapi.TYPE_STRING,
                required=False,
            ),
        ],
    )
    def get(self, request):
        actividad_codigo = request.query_params.get('actividad_codigo') or None
        client = GuaraniClient()
        comisiones = client.list_comisiones(actividad_codigo=actividad_codigo) or []
        result = []
        for com in comisiones:
            id_comision = com.get('comision')
            if not id_comision:
                continue
            detail = client.get_comision(id_comision) or {}
            if detail.get('horarios'):
                result.append(detail)
        return Response(result)
