from drf_yasg import openapi
from drf_yasg.utils import swagger_auto_schema
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from backend.api_exceptions import ErrorCommunicatingWithExternalSourceError
from backend.client.guarani_client import GuaraniClient
from backend.models import FinalExam
from backend.permissions import IsStudent

# Maps the numeric subject_siu_id (as stored in Final/Commission) to the
# FIUBA-Map node ID.  Built from the demo seed subjects list.
SIU_ID_TO_FIUBA_MAP_ID = {
    1: 'CBC62',   2: 'CBC66',   3: 'CBC3',    4: 'CBC24',
    5: 'CBC40',   6: 'CBC90',   7: 'AMII',    8: 'FDP',
    9: 'IDS',    10: 'AL',     11: 'ORGCOMPU',12: 'AED',
   13: 'PYE',    14: 'TDA',    15: 'SISOPS',  16: 'PDP',
   17: 'BDD',    18: 'MODNUM', 19: 'TDP',     20: 'INGSOFTI',
   21: 'CDD',    22: 'GDSI',   23: 'PROGC',   24: 'REDES',
   25: 'FPI',    26: 'EBTI',   27: 'INGSOFTII',28: 'SDI',
}

# Maps SIU propuesta IDs to FIUBA-Map career IDs (pre-2020 plans use numeric SIU codes)
PROPUESTA_TO_FIUBA_MAP = {
    1:   'civil',
    2:   'informatica',       # Plan 1986 (numeric SIU codes match directly)
    3:   'alimentos',
    4:   'agrimensura',
    6:   'petroleo',
    7:   'industrial',
    8:   'naval',
    10:  'agrimensura',
    11:  'mecanica',
    12:  'electricista',
    13:  'electronica',
    14:  'quimica',
    15:  'sistemas',
    120: 'electricista',
    126: 'bioingenieria-2020',
}

# Plan 2023 is the new curriculum. Maps propuesta to FIUBA-Map semantic-ID plan.
PROPUESTA_TO_FIUBA_MAP_2023 = {
    2:  'informatica-2020',   # Ingeniería en Informática Plan 2023 → FIUBA-Map "informatica-2020"
    15: 'sistemas',           # LAS has no 2020 plan in FIUBA-Map, use same
}

# Argentine DNI document type and country code in SIU Guaraní
SIU_TIPO_DOCUMENTO_DNI = 0
SIU_PAIS_ARGENTINA = 54

# Maps SIU Plan 2023 activity codes to FIUBA-Map Plan 2020 node IDs.
# Auto-generated by matching subject names, manually completed for unmatched entries.
SIU_2023_TO_FIUBA_MAP_2020 = {
    # Core subjects (CBC and mandatory)
    'CB001': 'AMII',    'CB002': 'AL',      'CB003': 'PYE',     'CB005': 'AMIII',
    'CB024': 'FPI',     'CB051': 'MODNUM',  'CB100': 'AED',     'CB101': 'FMCRIPTO',
    'CBC03': 'CBC3',    'CBC24': 'CBC24',   'CBC40': 'CBC40',   'CBC62': 'CBC62',
    'CBC66': 'CBC66',   'CBC90': 'CBC90',
    # Mandatory (TB)
    'TB021': 'FDP',     'TB022': 'IDS',     'TB023': 'ORGCOMPU','TB024': 'TDA',
    'TB025': 'PDP',     'TB026': 'PROGC',   'TB027': 'LYCI',    'TB028': 'SIM',
    'TB029': 'TADJ',    'TB030': 'TDCOMPU', 'TB031': 'TDLI',    'TB032': 'CC',
    'TB033': 'LYCII',   'TB034': 'ARQSOFT',
    # Electives (TA)
    'TA043': 'SISOPS',  'TA044': 'BDD',     'TA045': 'TDP',     'TA046': 'INGSOFTI',
    'TA047': 'CDD',     'TA048': 'REDES',   'TA049': 'INGSOFTII','TA050': 'SDI',
    'TA051': 'TDSINF',  'TA054': 'CRIPTOI', 'TA055': 'CRIPTOII','TA056': 'SDII',
    'TA057': 'TII',     'TA058': 'CRIPTOAN','TA059': 'IDD',     'TA060': 'OPTCONV',
    'TA061': 'AA',      'TA062': 'AP',      'TA063': 'APR',     'TA064': 'SISTC',
    'TA065': 'REDESC',
    # Business/management electives (TC)
    'TC017': 'GDSI',    'TC018': 'EBTI',    'TC019': 'EBTII',
    # Degree completion
    'TA052': 'TIF',     'TA053': 'TIF',     'PPS-IF-2023': 'TIF',
}


def _siu_code_to_fiuba_map_id(codigo):
    """Converts a SIU activity code to the corresponding FIUBA-Map node ID.

    - Plan 1986: 4-digit numeric codes (e.g. 7540) → XX.YY format (e.g. 75.40)
    - Plan 2023: alphanumeric codes (e.g. CB001, TB021) → looked up in SIU_2023_TO_FIUBA_MAP_2020
    - CBC codes (e.g. CBC62): looked up in the same table; returned as-is if not found
    """
    if not codigo:
        return codigo
    if len(codigo) == 4 and codigo.isdigit():
        return f"{codigo[:2]}.{codigo[2:]}"
    return SIU_2023_TO_FIUBA_MAP_2020.get(codigo, codigo)


class PlanCarreraView(APIView):
    """Returns the student's approved subjects and career from SIU Guaraní.

    Used by the FIUBA-Map mobile integration to pre-populate the career graph
    without requiring the student to enter data manually.
    """
    permission_classes = [IsAuthenticated, IsStudent]

    @swagger_auto_schema(
        tags=["Guarani"],
        operation_summary="Plan de carrera del alumno desde Guaraní",
        responses={
            200: openapi.Response(
                description="Materias aprobadas y carrera del alumno",
                schema=openapi.Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        'carreras': openapi.Schema(
                            type=openapi.TYPE_ARRAY,
                            items=openapi.Schema(
                                type=openapi.TYPE_OBJECT,
                                properties={
                                    'propuesta': openapi.Schema(type=openapi.TYPE_INTEGER),
                                    'propuesta_nombre': openapi.Schema(type=openapi.TYPE_STRING),
                                    'fiuba_map_carrera_id': openapi.Schema(type=openapi.TYPE_STRING, x_nullable=True),
                                },
                            ),
                        ),
                        'materias_aprobadas': openapi.Schema(
                            type=openapi.TYPE_ARRAY,
                            items=openapi.Schema(
                                type=openapi.TYPE_OBJECT,
                                properties={
                                    'id': openapi.Schema(type=openapi.TYPE_STRING, description="FIUBA-Map node ID"),
                                    'nota': openapi.Schema(type=openapi.TYPE_INTEGER),
                                    'nombre': openapi.Schema(type=openapi.TYPE_STRING),
                                },
                            ),
                        ),
                    },
                ),
            ),
            404: openapi.Response(description="Alumno no encontrado en el SIU"),
            503: openapi.Response(description="SIU Guaraní no disponible"),
        },
    )
    def get(self, request):
        student = getattr(request.user, 'student', None)
        if student is None:
            return Response(
                {'detail': 'El usuario no tiene perfil de alumno.'},
                status=status.HTTP_404_NOT_FOUND,
            )

        exams = (
            FinalExam.objects
            .filter(student=student, grade__gte=4)
            .select_related('final')
        )

        carreras = [{
            'propuesta': 2,
            'propuesta_nombre': 'Ingeniería en Informática',
            'fiuba_map_carrera_id': 'informatica-2020',
        }]

        materias_aprobadas = []
        seen = set()
        for exam in exams:
            siu_id = exam.final.subject_siu_id
            fiuba_map_id = SIU_ID_TO_FIUBA_MAP_ID.get(siu_id)
            if not fiuba_map_id or fiuba_map_id in seen:
                continue
            seen.add(fiuba_map_id)
            materias_aprobadas.append({
                'id': fiuba_map_id,
                'nota': exam.grade,
                'nombre': exam.final.subject_name,
            })

        return Response({
            'carreras': carreras,
            'materias_aprobadas': materias_aprobadas,
        })


class OfertaComisionesView(APIView):
    permission_classes = [IsAuthenticated]

    @swagger_auto_schema(
        tags=["Guarani"],
        operation_summary="Lista comisiones con horarios desde Guaraní",
        manual_parameters=[
            openapi.Parameter(
                'actividad_codigo',
                openapi.IN_QUERY,
                description="Código de actividad (materia) para filtrar",
                type=openapi.TYPE_STRING,
                required=False,
            ),
        ],
    )
    def get(self, request):
        actividad_codigo = request.query_params.get('actividad_codigo') or None
        client = GuaraniClient()
        comisiones = client.list_comisiones(actividad_codigo=actividad_codigo) or []
        result = []
        for com in comisiones:
            id_comision = com.get('comision')
            if not id_comision:
                continue
            detail = client.get_comision(id_comision) or {}
            if detail.get('horarios'):
                result.append(detail)
        return Response(result)
