# Generated by Django 3.1.2 on 2026-03-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_evaluation_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='evaluation_submissions/'),
        ),
        migrations.AddField(
            model_name='evaluationsubmission',
            name='submission_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationsubmission',
            name='submission_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
