# Generated by Django 3.1.2 on 2026-04-02 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_notification_usernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('location', models.CharField(blank=True, default='', max_length=300, verbose_name='Ubicación')),
                ('schedule', models.TextField(blank=True, default='', verbose_name='Horario de atención')),
                ('contact_info', models.TextField(blank=True, default='', verbose_name='Información de contacto')),
                ('procedures', models.TextField(blank=True, default='', verbose_name='Trámites')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['name'],
            },
        ),
    ]
