# Generated by Django 3.1.2 on 2026-03-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_evaluation_submission_grade_grader_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='requires_identity',
            field=models.BooleanField(default=False, verbose_name='Requiere verificación de identidad'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='requires_qr',
            field=models.BooleanField(default=False, verbose_name='Requiere escanear QR'),
        ),
    ]
