# Generated by Django 3.1.2 on 2026-03-17 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_optional_qr_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationsubmission',
            name='submission_url',
        ),
    ]
