# Generated by Django 3.1.2 on 2026-03-29 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0048_add_evaluation_status_and_gradeable_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationsubmission',
            old_name='status',
            new_name='submission_status',
        ),
    ]
