# Generated by Django 3.1.2 on 2026-04-03 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_auto_20260329_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationsubmission',
            name='file',
        ),
    ]
