# Generated by Django 3.1.2 on 2026-04-04 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_remove_evaluationsubmission_file'),
        ('backend', '0042_notification_usernotification'),
    ]

    operations = [
    ]
