# Generated by Django 3.1.2 on 2026-04-04 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_merge_20260404_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='evaluation_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nombre de Evaluacion'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='passing_grade',
            field=models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nota de Aprobacion'),
        ),
    ]
