# Generated by Django 3.1.2 on 2026-04-13 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_auto_20260404_1724'),
        ('backend', '0043_auto_20260409_2207'),
        ('backend', '0043_department'),
    ]

    operations = [
    ]
