# Generated by Django 3.1.2 on 2026-04-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_notification_image'),
        ('backend', '0053_merge_20260413_2247'),
    ]

    operations = [
    ]
