# Generated by Django 3.1.2 on 2026-04-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_merge_20260416_1917'),
        ('backend', '0055_academiccalendarevent'),
    ]

    operations = [
    ]
