# Generated by Django 3.1.2 on 2026-05-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_notification_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='location_valid',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ubicacion valida'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='attendanceqrcode',
            name='campus',
            field=models.CharField(blank=True, choices=[('las_heras', 'Las Heras'), ('paseo_colon', 'Paseo Colón')], max_length=20, null=True, verbose_name='Sede'),
        ),
        migrations.AddField(
            model_name='attendanceqrcode',
            name='mode',
            field=models.CharField(choices=[('qr', 'QR'), ('location', 'Ubicación')], default='qr', max_length=10, verbose_name='Modo de asistencia'),
        ),
    ]
