# Generated by Django 3.1.2 on 2026-05-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_calendar_reminders'),
        ('backend', '0058_user_github_url'),
    ]

    operations = [
    ]
