# Generated by Django 3.1.2 on 2026-05-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_merge_20260509_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsubmission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
