# Generated by Django 3.1.2 on 2026-05-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_merge_20260509_2029'),
        ('backend', '0066_seed_digital_forms'),
    ]

    operations = [
    ]
