# Generated by Django 3.1.2 on 2026-05-13 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_dept_admins'),
        ('backend', '0067_merge_20260510_2038'),
    ]

    operations = [
    ]
