# Generated by Django 3.1.2 on 2026-05-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0068_evaluationsubmission_submission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsubmission',
            name='feedback_text',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback del profesor'),
        ),
    ]
