# Generated by Django 3.1.2 on 2026-05-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0070_evaluation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsubmission',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de archivo original'),
        ),
    ]
