# Generated by Django 3.1.2 on 2026-05-15 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0070_remove_teacher_profile'),
        ('backend', '0059_attendance_qr_mode_qr_location'),
        ('backend', '0071_evaluationsubmission_original_filename'),
    ]

    operations = [
    ]
