# Generated by Django 3.1.2 on 2026-05-18 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0071_merge_20260513_2206'),
        ('backend', '0073_staff_is_bedelia'),
    ]

    operations = [
    ]
