# Generated by Django 3.1.2 on 2026-05-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0074_merge_20260518_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Imagen'),
        ),
    ]
