# Generated by Django 3.1.2 on 2026-05-31 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0076_final_commissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siu_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='StudentCareer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(blank=True, default='', max_length=50)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_careers', to='backend.career')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_careers', to='backend.student')),
            ],
            options={
                'verbose_name': 'Carrera de Alumno',
                'verbose_name_plural': 'Carreras de Alumnos',
                'unique_together': {('student', 'career')},
            },
        ),
    ]
