# Generated by Django 5.2.14 on 2026-05-27 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0076_auto_20260525_2310'),
        ('backend', '0076_final_commissions'),
    ]

    operations = [
    ]
