# Generated by Django 3.1.2 on 2026-06-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0077_user_profile_photo'),
        ('backend', '0077_career_student_career'),
    ]

    operations = [
    ]
