# Generated by Django 3.1.2 on 2026-05-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0077_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL de acción'),
        ),
    ]
