# Generated by Django 5.2.14 on 2026-06-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0077_career_student_career'),
        ('backend', '0077_merge_0076_auto_20260525_2310_0076_final_commissions'),
    ]

    operations = [
    ]
