# Generated by Django 5.2.14 on 2026-06-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0078_merge_20260602_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentcareer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
