# Generated by Django 5.2.14 on 2026-05-29 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0077_merge_0076_auto_20260525_2310_0076_final_commissions'),
        ('backend', '0079_study_group'),
    ]

    operations = [
    ]
