# Generated by Django 3.1.2 on 2026-05-27 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0081_form_submission_recipient_fields'),
        ('backend', '0076_final_commissions'),
    ]

    operations = [
    ]
