# Generated by Django 5.2.14 on 2026-06-03 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0077_catedra_calendar'),
        ('backend', '0078_merge_20260602_2105'),
        ('backend', '0079_alter_career_id_alter_studentcareer_id'),
        ('backend', '0081_alter_contact_id_alter_groupmembership_id_and_more'),
        ('backend', '0083_alter_formdocumentsource_form_document_source'),
    ]

    operations = [
    ]
